### ISSUE TITLE
Cannot change S3 region via ~/.aws/ when running flyio_auth()

### ISSUE THREAD

**Issue by afeierman** [atlanhq/flyio#37]
Even if a default region other than us-east-1 is specified in ~/.aws/credentials file (or ~/.aws/config), flyio_auth() does not change value sent to Sys.SetEnv(). 

I think issue stems from the file processing in `.awscred_profile()`. Custom region setting works when values are provided directly into flyio_auth() via the auth_list parameter.

**Comment by himanshu-sikaria** [comment]
@afeierman sorry for the delayed response. You are right, the issue seems to be how `.awscred_profile` is currently parsing the ~/.aws/credentials file. Will add region to it in the next release.

**Comment by himanshu-sikaria** [comment]
Was a quick fix, can you install using github and verify if this solves for you.

**Comment by afeierman** [comment]
Awesome, thanks @himanshu-sikaria. the package is great and improves our existing workflow
